FROM mambaorg/micromamba:focal-cuda-11.7.0 AS conda_torch

# The version above should match the version in nvidia-smi.
# On abel the drivers currently support version 11.7 must be used for the torch installation.
#
# see
# - https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
# - https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
# in each release.
#
# Build
# docker build -t conda_torch:11.7 .
#
# Run
# docker run --gpus all -it conda_torch:11.7
SHELL ["/bin/bash", "-c"]

USER root
RUN apt-get -y update && apt-get install -y git libtiff5

USER $MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/environment.yml
RUN micromamba install -y -n base -f /tmp/environment.yml && micromamba clean --all --yes
