name: conda_torch
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.10
  - pandas>=1.3.3
  - scikit-learn>=0.24.2
  - numpy>=1.21.2
  - joblib>=1.0.1
  - openpyxl
  - umap-learn
  - loguru
  - h5py
  - anndata
  - scanpy
  - jax-cuda>=0.4.23
  - mkl=2024.0.0
  - pytorch=2.0.1
  - cuda-version=11.7
  - pytorch-cuda=11.7
  - pytorch_geometric=2.5.3
  - torchvision>=0.15.2
  - torchaudio>=2.0.2
  - jupyterlab>=4.1.6
  - ipywidgets>=8.1.2
 # - pip:  # uncomment to install directly from pip if they are not in conda
 #   - stg
